import CategoryItems from "./CategoryItems";

/* eslint-disable react/prop-types */
function Digital({ device }) {
  const digital = {
    title: "همه محصولات کالای دیجیتال",
    maxDesktopColumn: 4,
    items: [
      {
        itemTile: "لپ تاپ",
        colNumber: 1,
        elements: [
          { name: "لپ تاپ ایسوس" },
          { name: "لپ تاپ لنوو" },
          { name: "مک بوک" },
          { name: "لپ تاپ HP" },
          { name: "لپ تاپ دل" },
          { name: "لپ تاپ ایسر" },
          { name: "لپ تاپ ام اس آی" },
          { name: "لپ تاپ ROG" },
          { name: "لپ تاپ TUF Gaming" },
          { name: "لپ تاپ LOQ" },
          { name: "لپ تاپ ideapad slim3" },
          { name: "لپ تاپ Vivobook" },
          { name: "لپ تاپ Victus" },
          { name: "لپ تاپ کاستوم" },
          { name: "لپ تاپ استوک" },
        ],
      },
      {
        itemTile: "لوازم جانبی لپ تاپ",
        colNumber: 1,
        elements: [
          { name: "شارژر لپ تاپ" },
          { name: "کیف لپ تاپ" },
          { name: "کول پد" },
          { name: "استیکر لپ تاپ" },
        ],
      },
      {
        itemTile: "کنسول بازی",
        colNumber: 1,
        elements: [
          { name: "ps5" },
          { name: "ps5 slim" },
          { name: "ps4" },
          { name: "xbox" },
        ],
      },
      {
        itemTile: "وسایل گیمینگ",
        colNumber: 1,
        elements: [
          { name: "ست گیمینگ" },
          { name: "دسته بازی" },
          { name: "بازی ps5" },
          { name: "بازی ps4" },
          { name: "دیسک های بازی" },
          { name: "فرمان بازی" },
        ],
      },
      {
        itemTile: "کامپیوتر",
        colNumber: 1,
        elements: [
          { name: "all in one" },
          { name: "mini pc" },
          { name: "قلم نوری" },
          { name: "رم ریدر" },
          { name: "ماوس پد" },
          { name: "کیس اسمبل شده" },
        ],
      },
      {
        itemTile: "کیبورد",
        colNumber: 1,
        elements: [
          { name: "کیبورد گیمینگ" },
          { name: "کیبورد بی سیم" },
          { name: "کیبورد مکانیکال" },
        ],
      },
      {
        itemTile: "کیس کامپیوتر",
        colNumber: 1,
        elements: [{ name: "کیس گیمینگ" }],
      },
      {
        itemTile: "ماوس",
        colNumber: 1,
        elements: [{ name: "ماوس گیمینگ" }, { name: "ماوس بی سیم" }],
      },
      {
        itemTile: "مانیتور",
        colNumber: 1,
        elements: [{ name: "مانیتور OLED" }],
      },
      {
        itemTile: "اسپیکر",
        colNumber: 1,
        elements: [
          { name: "اسپیکر بلوتوثی" },
          { name: "اسپیکر jbl" },
          { name: "اسپیکر هارمن کاردن" },
          { name: "اسپیکر سونی" },
          { name: "اسپیکر تسکو" },
          { name: "اسپیکر مکسیدر" },
          { name: "اسپیکر میکرولب" },
          { name: "پارتی باکس" },
        ],
      },
      {
        itemTile: "قطعات کامپیوتر",
        colNumber: 1,
        elements: [
          { name: "پردازنده(cpu)" },
          { name: "کارت گرافیک" },
          { name: "مادر برد" },
          { name: "دانگل بلوتوث" },
        ],
      },
      {
        itemTile: "هدفون",
        colNumber: 2,
        elements: [
          { name: "هدفون بی سیم" },
          { name: "هدفون اپل (ایرپاد)" },
          { name: "هدفون بیتس" },
          { name: "هدفون سونی" },
          { name: "هدفون سامسونگ(ایرپادز)" },
          { name: "هدفون شیائومی" },
          { name: "هدفون جی بی ال" },
          { name: "هدفون ریزر" },
        ],
      },
      {
        itemTile: "ساعت و مچ بند هوشمند",
        colNumber: 2,
        elements: [
          { name: "ساعت هوشمند سامسونگ" },
          { name: "ساعت هوشمند شیائومی" },
          { name: "اپل واچ" },
          { name: "بند اپل واچ" },
          { name: "بند ساعت هوشمند" },
          { name: "لوازم جانبی ساعت هوشمند" },
        ],
      },
      {
        itemTile: "دوربین",
        colNumber: 2,
        elements: [
          { name: "دوربین فیلم‌برداری" },
          { name: "دوربین کنون" },
          { name: "دوربین سونی" },
          { name: "دوربین چاپ سریع" },
          { name: "رینگ لایت" },
          { name: "پایه دوربین" },
          { name: "لنز دوربین" },
          { name: "کارت حافظه" },
        ],
      },
      {
        itemTile: "تجهیزات ذخیره سازی اطلاعات",
        colNumber: 2,
        elements: [
          { name: "هارد ssd" },
          { name: "هارد اینترال" },
          { name: "هارد اکسترنال" },
        ],
      },
      {
        itemTile: "فلش",
        colNumber: 2,
        elements: [
          { name: "فلش ۲۵۶ گیگ" },
          { name: "فلش ۱۲۸ گیگ" },
          { name: "فلش ۶۴ گیگ" },
          { name: "فلش ۳۲ گیگ" },
          { name: "فلش ۱۶ گیگ" },
        ],
      },
      {
        itemTile: "پاور بانک",
        colNumber: 2,
        elements: [
          { name: "فست شارژ" },
          { name: "پاور بانک شیائومی" },
          { name: "پاور بانک انکر" },
          { name: "پاور بانک اپل" },
          { name: "پاور بانک سامسونگ" },
          { name: "پاور بانک انرجایزر" },
        ],
      },
      {
        itemTile: "باتری",
        colNumber: 2,
        elements: [{ name: "باتری لیتیومی" }, { name: "باتری قلمی" }],
      },
      {
        itemTile: "پرینتر",
        colNumber: 3,
        elements: [
          { name: "پرینتر سه بعدی" },
          { name: "پرینتر حرارتی" },
          { name: "پرینتر رنگی" },
          { name: "پرینتر لیبل زن" },
          { name: "پرینتر اچ پی" },
        ],
      },
      {
        itemTile: "ماشین های اداری",
        colNumber: 3,
        elements: [
          { name: "کابل پرینتر" },
          { name: "کارتریج" },
          { name: "اسکنر" },
          { name: "تلفن" },
          { name: "بارکد خوان" },
          { name: "ویدئو وال" },
          { name: "ویدئو پروژکتور" },
          { name: "دستگاه حضور غیاب" },
        ],
      },
      {
        itemTile: "تجهیزات شبکه و ارتباطات",
        colNumber: 3,
        elements: [
          { name: "هاب USB" },
          { name: "سوییچ" },
          { name: "هاب سوئیچ" },
          { name: "تجهیزات ویدئویی" },
          { name: "کارت شبکه" },
          { name: "کامپیوتر سرور" },
          { name: "رک شبکه و سرور" },
          { name: "پچ پنل" },
          { name: "پرینت سرور" },
          { name: "آداپتور شبکه" },
          { name: "اسپلیتر" },
        ],
      },
      {
        itemTile: "مودم",
        colNumber: 3,
        elements: [
          { name: "مودم جیبی" },
          { name: "موردن ایرانسل" },
          { name: "مودم همراه اول" },
          { name: "توسعه دهنده محدوده بی سیم" },
          { name: "روتر و اکسس پوینت" },
        ],
      },
      {
        itemTile: "تجهیزات امنیتی و نظارتی",
        colNumber: 3,
        elements: [{ name: "دوربین مدار بسته" }],
      },
      {
        itemTile: "تبلت",
        colNumber: 4,
        elements: [],
      },
      {
        itemTile: "ایپد",
        colNumber: 4,
        elements: [{ name: "ایپد ایر" }, { name: "ایپد پرو" }],
      },
      {
        itemTile: "خانه هوشمند",
        colNumber: 4,
        elements: [],
      },
      {
        itemTile: "برند های برتر",
        colNumber: 4,
        elements: [
          { name: "شیائومی" },
          { name: "سامسونگ" },
          { name: "اپل" },
          { name: "هواوی" },
          { name: "آنر" },
          { name: "ریلمی" },
          { name: "توشیبا" },
          { name: "تکنو" },
          { name: "ایرانسل" },
          { name: "مبین نت" },
          { name: "نینتندو" },
          { name: "بیتس" },
          { name: "جی بی ال" },
          { name: "وان مور" },
          { name: "تی پی لینک" },
          { name: "دی لینک" },
          { name: "کیو سی وای" },
        ],
      },
      {
        itemTile: "داغ ترین ها",
        colNumber: 4,
        elements: [
          { name: "اپل واچ 10" },
          { name: "گیمینگ" },
          { name: "هدفون گربه ای" },
          { name: "هدفون" },
          { name: "مک بوک ایر  m 1" },
          { name: "مک بوک ایر  m2" },
          { name: "بیتس" },
          { name: "مک بوک ایر  m3" },
          { name: "مک بوک پرو m3" },
          { name: "مک بوک پرو max m3" },
        ],
      },
      {
        itemTile: "لپ تاپ",
        colNumber: 1,
        elements: [
          { name: "لپ تاپ ایسوس" },
          { name: "لپ تاپ لنوو" },
          { name: "مک بوک" },
          { name: "لپ تاپ HP" },
          { name: "لپ تاپ دل" },
          { name: "لپ تاپ ایسر" },
          { name: "لپ تاپ ام اس آی" },
          { name: "لپ تاپ ROG" },
          { name: "لپ تاپ  TUF Gaming" },
          { name: "لپ تاپ LOQ" },
          { name: "لپ تاپ ideapad slim3" },
          { name: "لپ تاپ  Vivobook" },
          { name: "لپ تاپ Victus" },
          { name: "لپ تاپ کاستوم" },
          { name: "لپ تاپ استوک" },
        ],
      },
      {
        itemTile: "لوازم جانبی لپ تاپ",
        colNumber: 1,
        elements: [
          { name: "شارژر لپ تاپ" },
          { name: "کیف لپ تاپ" },
          { name: "کول پد" },
          { name: "استیکر لپ تاپ" },
        ],
      },
      {
        itemTile: "کنسول بازی",
        colNumber: 1,
        elements: [
          { name: "ps5" },
          { name: "ps5 slim" },
          { name: "ps4" },
          { name: "xbox" },
        ],
      },
      {
        itemTile: "وسایل گیمینگ",
        colNumber: 1,
        elements: [
          { name: "ست گیمینگ" },
          { name: "دسته بازی" },
          { name: "بازی ps5" },
          { name: "بازی ps4" },
          { name: "دیسک های بازی" },
          { name: "فرمان بازی" },
        ],
      },
      {
        itemTile: "کامپیوتر",
        colNumber: 1,
        elements: [
          { name: "all in one" },
          { name: "mini pc" },
          { name: "قلم نوری" },
          { name: "رم ریدر" },
          { name: "ماوس پد" },
          { name: "کیس اسمبل شده" },
        ],
      },
      {
        itemTile: "کیبورد",
        colNumber: 1,
        elements: [
          { name: "کیبورد گیمینگ" },
          { name: "کیبورد بی سیم" },
          { name: "کیبورد مکانیکال" },
        ],
      },
      {
        itemTile: "کیس کامپیوتر",
        colNumber: 1,
        elements: [{ name: "کیس گیمینگ" }],
      },
      {
        itemTile: "ماوس",
        colNumber: 1,
        elements: [{ name: "ماوس گیمینگ" }, { name: "ماوس بی سیم" }],
      },
      {
        itemTile: "مانیتور",
        colNumber: 1,
        elements: [{ name: "مانیتور OLED" }],
      },
      {
        itemTile: "اسپیکر",
        colNumber: 1,
        elements: [
          { name: "اسپیکر بلوتوثی" },
          { name: "اسپیکر jbl" },
          { name: "اسپیکر هارمن کاردن" },
          { name: "اسپیکر سونی" },
          { name: "اسپیکر تسکو" },
          { name: "اسپیکر مکسیدر" },
          { name: "اسپیکر میکرولب" },
          { name: "پارتی باکس" },
        ],
      },
      {
        itemTile: "قطعات کامپیوتر",
        colNumber: 1,
        elements: [
          { name: "پردازنده(cpu)" },
          { name: "کارت گرافیک" },
          { name: "مادر برد" },
          { name: "دانگل بلوتوث" },
        ],
      },
      {
        itemTile: "رم کامپیوتر",
        colNumber: 1,
        elements: [],
      },
      {
        itemTile: "هدفون",
        colNumber: 2,
        elements: [
          { name: "هدفون بی سیم" },
          { name: "هدفون اپل (ایرپاد)" },
          { name: "هدفون بیتس" },
          { name: "هدفون سونی" },
          { name: "هدفون سامسونگ(ایرپادز)" },
          { name: "هدفون شیائومی" },
          { name: "هدفون جی بی ال" },
          { name: "هدفون ریزر" },
        ],
      },
      {
        itemTile: "هدست",
        colNumber: 2,
        elements: [],
      },
      {
        itemTile: "ساعت و مچ بند هوشمند",
        colNumber: 2,
        elements: [
          { name: "ساعت هوشمند سامسونگ" },
          { name: "ساعت هوشمند شیائومی" },
          { name: "اپل واچ" },
          { name: "بند اپل واچ" },
          { name: "بند ساعت هوشمند" },
          { name: "لوازم جانبی ساعت هوشمند" },
        ],
      },
      {
        itemTile: "دوربین",
        colNumber: 2,
        elements: [
          { name: "دوربین فیلم‌برداری" },
          { name: "دوربین کنون" },
          { name: "دوربین سونی" },
          { name: "دوربین چاپ سریع" },
          { name: "رینگ لایت" },
          { name: "پایه دوربین" },
          { name: "لنز دوربین" },
          { name: "کارت حافظه" },
        ],
      },
      {
        itemTile: "تجهیزات ذخیره سازی اطلاعات",
        colNumber: 2,
        elements: [
          { name: "هارد ssd" },
          { name: "هارد اینترال" },
          { name: "هارد اکسترنال" },
        ],
      },
      {
        itemTile: "فلش",
        colNumber: 2,
        elements: [
          { name: "فلش ۲۵۶ گیگ" },
          { name: "فلش ۱۲۸ گیگ" },
          { name: "فلش ۶۴ گیگ" },
          { name: "فلش ۳۲ گیگ" },
          { name: "فلش ۱۶ گیگ" },
        ],
      },
      {
        itemTile: "پاور بانک",
        colNumber: 2,
        elements: [
          { name: "فست شارژ" },
          { name: "پاور بانک شیائومی" },
          { name: "پاور بانک انکر" },
          { name: "پاور بانک اپل" },
          { name: "پاور بانک سامسونگ" },
          { name: "پاور بانک انرجایزر" },
        ],
      },
      {
        itemTile: "باتری",
        colNumber: 2,
        elements: [{ name: "باتری لیتیومی" }, { name: "باتری قلمی" }],
      },
      {
        itemTile: "پرینتر",
        colNumber: 3,
        elements: [
          { name: "پرینتر سه بعدی" },
          { name: "پرینتر حرارتی" },
          { name: "پرینتر رنگی" },
          { name: "پرینتر لیبل زن" },
          { name: "پرینتر اچ پی" },
        ],
      },
      {
        itemTile: "ماشین های اداری",
        colNumber: 3,
        elements: [
          { name: "کابل پرینتر" },
          { name: "کارتریج" },
          { name: "اسکنر" },
          { name: "تلفن" },
          { name: "بارکد خوان" },
          { name: "ویدئو وال" },
          { name: "ویدئو پروژکتور" },
          { name: "دستگاه حضور غیاب" },
        ],
      },
      {
        itemTile: "تجهیزات شبکه و ارتباطات",
        colNumber: 3,
        elements: [
          { name: "هاب USB" },
          { name: "سوییچ" },
          { name: "هاب سوئیج" },
          { name: "تجهیزات ویدئویی" },
          { name: "کارت شبکه" },
          { name: "کامپیوتر سرور" },
          { name: "رک شبکه و سرور" },
          { name: "پچ پنل" },
          { name: "پرینت سرور" },
          { name: "آداپتور شبکه" },
          { name: "اسپلیتر" },
          { name: "کابل شبکه (LAN)" },
          { name: "کابل cat6" },
          { name: "کابل کمبود" },
          { name: "کارت و ماژول" },
          { name: "لوازم جانبی NAS وسرور" },
          { name: "یو پی اس (UPS)" },
          { name: "ابزار شبکه" },
          { name: "آنتن تقویتی" },
          { name: "مبدل فیبر نوری" },
          { name: "سیم آنتن" },
        ],
      },
    ],
  };

  return <CategoryItems device={device} Items={digital} />;
}

export default Digital;
